
# State machine for reading values from MCU
IDLE = 0
READING = 1

# MCU API Misc
EMPTY = b''

# MCU API Control Characters
START_TRANSMISSION = b'\x01'
END_TRANSMISSION = b'\x03'
ACKNOWLEDGE = b'\x06'
NEGATIVE_ACKNOWLEDGE = b'\x15'

# MCU API Endpoints
GET_SYSTEM_SNAPSHOT_OPCODE = b'\xA0'
GET_SENSOR_STATE_OPCODE = b'\xA1'
GET_ACTUATOR_STATE_OPCODE = b'\xA2'
SET_ACTUATOR_STATE_OPCODE = b'\xB0'
